#!/usr/bin/env python3
"""Refresh the checked-in HTML using GitHub's GFM renderer; no site build needed."""

import hashlib
import html
import json
from pathlib import Path
import re
import subprocess
import sys

ROOT = Path(__file__).resolve().parents[1]
SOURCE = ROOT / "docs/firmware_reference.md"
REPOSITORY = "https://github.com/RyanJarv/AuroraSwitch/blob/main/"
COLORS = {
    "Blue": "#3787ff", "Green": "#35bf58", "Cyan": "#32c9ce",
    "Magenta": "#d855d5", "Amber": "#dc9a25", "Yellow": "#ead342",
    "White": "#fff", "Orange": "#ec8734", "Violet": "#a273e7",
    "Mint": "#79dcaa", "Pale red": "#ec9292", "Azure": "#3ea7dc",
}


def slug(heading: str) -> str:
    """Match the reference's GitHub heading links, including doubled hyphens."""
    return re.sub(r"[^\w\- ]", "", html.unescape(heading).lower()).replace(" ", "-")


def render() -> str:
    """Render Markdown once, then add navigation and static HTML styling."""
    source = SOURCE.read_text()
    digest = hashlib.sha256(SOURCE.read_bytes()).hexdigest()

    def absolute_link(match: re.Match) -> str:
        target = match[1]
        if target.startswith(("#", "https://", "http://")):
            return match[0]
        file, separator, anchor = target.partition("#")
        relative = (SOURCE.parent / file).resolve().relative_to(ROOT)
        return f"]({REPOSITORY}{relative.as_posix()}{separator}{anchor})"

    source = re.sub(r"\]\(([^)]+)\)", absolute_link, source)
    response = subprocess.run(
        ["gh", "api", "markdown", "--input", "-"],
        input=json.dumps({"text": source, "mode": "gfm"}),
        text=True, capture_output=True, check=True,
    )
    body = re.sub(
        r"<h([1-6])>(.*?)</h\1>",
        lambda m: f'<h{m[1]} id="{slug(m[2])}">{m[2]}</h{m[1]}>',
        response.stdout, flags=re.S,
    )
    for name, color in COLORS.items():
        body = body.replace(
            f"<td>{name}</td>",
            f'<td><span class="swatch" style="background:{color}" aria-hidden="true"></span>{name}</td>',
        )
    return f'''<!doctype html>
<!-- Generated by scripts/render_reference.py; edit docs/firmware_reference.md. -->
<html lang="en">
<head>
<meta charset="utf-8">
<meta name="viewport" content="width=device-width, initial-scale=1">
<meta name="reference-sha256" content="{digest}">
<meta name="description" content="AuroraSwitch firmware colors, knobs, buttons, gates and modes.">
<title>AuroraSwitch · Firmware reference</title>
<style>
:root {{ color-scheme: light dark; --bg:#fafafa; --fg:#222; --line:#d1d5db; --accent:#175bb5; --cell:#f0f2f5; }}
@media (prefers-color-scheme: dark) {{ :root {{ --bg:#171a20; --fg:#e6e9ef; --line:#454b56; --accent:#91baff; --cell:#222731; }} }}
* {{ box-sizing:border-box; }}
html {{ scroll-padding-top:4rem; }}
body {{ margin:0; background:var(--bg); color:var(--fg); font:16px/1.6 system-ui,sans-serif; }}
nav {{ position:sticky; top:0; background:var(--bg); border-bottom:1px solid var(--line); padding:.65rem max(1rem,calc((100vw - 960px)/2)); display:flex; gap:1.2rem; flex-wrap:wrap; z-index:1; }}
main {{ max-width:960px; margin:auto; padding:1rem 1rem 4rem; }}
a {{ color:var(--accent); text-underline-offset:.15em; }}
h1 {{ line-height:1.2; }}
h2 {{ margin-top:2.5rem; border-top:1px solid var(--line); padding-top:1rem; line-height:1.3; }}
markdown-accessiblity-table {{ display:block; overflow-x:auto; }}
table {{ width:100%; border-collapse:collapse; font-size:.95rem; }}
th,td {{ text-align:left; vertical-align:top; padding:.55rem .7rem; border:1px solid var(--line); }}
th {{ background:var(--cell); }}
td:first-child {{ min-width:8rem; }}
code {{ background:var(--cell); padding:.1rem .25rem; border-radius:3px; overflow-wrap:anywhere; }}
.swatch {{ display:inline-block; width:.9rem; height:.9rem; border:1px solid #777; border-radius:50%; margin-right:.45rem; }}
@media print {{ nav {{ display:none; }} body {{ font-size:11pt; }} h2 {{ break-after:avoid; }} tr {{ break-inside:avoid; }} }}
</style>
</head>
<body>
<nav aria-label="Reference navigation">
<a href="#color-lookup">Colors</a>
<a href="https://github.com/RyanJarv/AuroraSwitch/blob/main/docs/user_guide.md">Setup</a>
<a href="https://github.com/RyanJarv/AuroraSwitch">GitHub</a>
</nav>
<main>
{body}
</main>
</body>
</html>
'''


if __name__ == "__main__":
    try:
        sys.stdout.write(render())
    except subprocess.CalledProcessError as error:
        sys.stderr.write(error.stderr)
        raise SystemExit(error.returncode) from error
